# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-02-22 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200222_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
